apiVersion: v1
kind: Service
metadata:
  name: orbeon
  namespace: orbeon
spec:
  type: NodePort
  selector:
    app: orbeon
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080