- name: Apply MinIO PV and PVC
  kubernetes.core.k8s:
    state: present
    kubeconfig: /home/johnarmis4/.kube/config
    src: "{{ playbook_dir }}/../../k8s-manifests/storage/minio-pv.yml"
  delegate_to: localhost

- name: Apply PostgreSQL PV and PVC
  kubernetes.core.k8s:
    state: present
    kubeconfig: /home/johnarmis4/.kube/config
    src: "{{ playbook_dir }}/../../k8s-manifests/storage/postgres-pv.yml"
  delegate_to: localhost

- name: Apply Orbeon PV and PVC
  kubernetes.core.k8s:
    state: present
    kubeconfig: /home/johnarmis4/.kube/config
    src: "{{ playbook_dir }}/../../k8s-manifests/storage/orbeon-pv.yml"
  delegate_to: localhost
