apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: postgres
  namespace: storage
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`postgres.local`)
      kind: Rule
      services:
        - name: postgres
          port: 5432
